# Generated by Django 5.0.6 on 2024-06-05 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_music', '0003_moodentry_owner_moodplaylist_owner_alter_mood_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_mood_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
