# Generated by Django 5.0.6 on 2024-06-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_music', '0004_alter_moodentry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodplaylist',
            name='spotify_playlist_id',
        ),
    ]
