# Generated by Django 5.0.6 on 2024-06-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_music', '0005_remove_moodplaylist_spotify_playlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='spotify_id',
        ),
    ]
