# Generated by Django 5.0.6 on 2024-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_music', '0006_remove_song_spotify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='mood_playlist',
        ),
        migrations.AddField(
            model_name='song',
            name='mood_playlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='songs', to='mood_music.moodplaylist'),
        ),
    ]
